within InaMo.Components;
package IonCurrents
  extends Modelica.Icons.VariantsPackage;
  import InaMo.Interfaces.*;
  import InaMo.Functions.Fitting.*;
  import InaMo.Functions.Biochemical.*;
  import InaMo.Concentrations.Basic.*;
  import InaMo.Concentrations.Atrial.*;
  import InaMo.Concentrations.Atrioventricular.*;
end IonCurrents;
